### ISSUE TITLE
minor issue building the script

### ISSUE THREAD

**Issue by homexkai** [amitxv/service-list-builder#1]
I don't know if it's a me problem but I seem to be getting this problems while trying to build the script.

<img width="610" alt="buildererror" src="https://github.com/amitxv/service-list-builder/assets/150613646/9a578fb8-20fa-400c-9502-20f026c0b131">

**Comment by amitxv** [comment]
It's not an issue. The program is simply telling you those binaries don't exist so it won't be added to script because there is nothing to rename.
