### ISSUE TITLE
'service-list-builder.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by xsangu** [amitxv/service-list-builder#2]
I got this error and i dont know what to do " 'service-list-builder.exe' is not recognized as an internal or external command,
operable program or batch file." I even tried older versions but it still doesnt work.
![image](https://github.com/amitxv/service-list-builder/assets/160313808/78b5a16a-6cd5-4a09-bd35-25551d6b5401)

**Comment by amitxv** [comment]
You need to change your current directory to the ``service-list-builder`` folder.

https://www.digitalcitizen.life/command-prompt-how-use-basic-commands
